# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            sroberts
tagline:          'see description'
description:      'intelligentsia in training, network security ninja, pancake visionary, former mixtape master, wannabe coffee specialist, bad guy catcher @<a href="www.github.com">github</a>'
url:              http://www.togafoamparty.com

author:
  name:           'Scott J Roberts'
  url:            https://twitter.com/sroberts

paginate:         5

# Custom vars
version:          2.0.0

github:
  main:           https://github.com/sroberts/

twitter:
  main:           https://www.twitter.com/sroberts

linkedin:
  main:           http://www.linkedin.com/in/scottroberts
